name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  test-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: |
          cd build/app
          npm install
      - name: Run basic tests
        run: |
          cd build/app
          npm test || echo "No test script found, continuing..."

  tests-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Python dependencies
        run: |
          pip install requests pytest
      
      - name: Build Docker image for testing
        run: |
          cd build/app
          docker build -t swaggerapi-test:latest .
      
      - name: Run Docker container
        run: |
          docker run -d -p 3206:3206 --name swaggerapi-test swaggerapi-test:latest
          sleep 10
      
      - name: Run Python integration tests
        run: |
          cd build
          python test_simple.py
          python test_prototype_pollution.py
      
      - name: Stop Docker container
        if: always()
        run: |
          docker stop swaggerapi-test || true
          docker rm swaggerapi-test || true

  build-and-push:
    needs: [test-install, tests-python]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ORGA }}
          password: ${{ secrets.DOCKER_OAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build/app
          file: ./build/app/Dockerfile
          push: true
          tags: cyberctf/swaggerapi-prototype-pollution:latest
      - name: Update DockerHub README
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
          repository: cyberctf/swaggerapi-prototype-pollution
          readme-filepath: ./README.md